set encoding=utf-8

"set t_Co=16
set t_Co=256
"colorscheme lunaperche

"always show cursor location
set ruler

"when searching: 'l' matches all, 'L' matches uppercase
set ignorecase
set smartcase

"when searching: move cursor to matching string as you type
set incsearch

"display line numbers
set number
"display relative line numbers
set relativenumber

"highlight space before width end
set colorcolumn=100
"wrap lines at 99 characters
set textwidth=99

"no bells: eb = errorbell, vb = visualbell
set noeb
set novb

"key binding when in normal mode
noremap <up> <nop>
noremap <down> <nop>
noremap <right> <nop>
noremap <left> <nop>
inoremap kj <Esc>
"deal with 'system reboot' wall messages
"noremap <F6> :redraw!<cr>

"programming: keyword coloring
syntax on
"programming: auto-indention
filetype plugin indent on

"whitespace edits...
set shiftwidth=4      "\t is 4 \s
set tabstop=4     "column width of \t NOTE: CONVENTIONAL USE IS 8
set expandtab     "fill \t with \s instead of using \t
set softtabstop=4 "\t is 4\s
set smarttab

"from ffmpeg dev's formatting conventions:
set cindent
set cinoptions=(0
"allow tab character in Makefiles
autocmd FileType make,automake set noexpandtab shiftwidth=8 softtabstop=8
"highlight trailing whitespace
highlight ForbiddenWhitespace ctermbg=red guibg=red
match ForbiddenWhitespace /\s\+$\|\t/
"but not when typing on that line
autocmd InsertEnter * match ForbiddenWhitespace /\t\|\s\+\%#\@<!$/

"save history when switching buffers
set hidden

"show matching parens, brackets, etc
set showmatch

"filename in title bar
set title

"correct exit misspellings
command! W w
command! Q q
command! Wq wq
command! WQ wq

"template for build scripts
:autocmd BufNewFile build.sh 0r ~/.vim/templates/template.build
"template for c programming
:autocmd BufNewFile *.c 0r ~/.vim/templates/template.c
"template for CMake-ified projects
:autocmd BufNewFile CMakeLists.txt 0r ~/.vim/templates/template.cmake
"template for python scripts
:autocmd BufNewFile *.py 0r ~/.vim/templates/template.py
"template for shell scripts
:autocmd BufNewFile *.sh 0r ~/.vim/templates/template.sh
